export enum GrocerieType {
    COFFEE=1,
    JUICE=2,
    SODA=3,
    TEA=4,
    SANDWICHLOAV=5,
    DINNERROLL=6,
    TORTILLA=7,
    BAGEL=8,
    SPAGHETISAUCE=0,
    KETCHUP=10,
    CHEESES=11,
    EGGS=12,
    MILK=13,
    YOGURT=14,
    BUTTER=15,
    CEREAL=16,
    FLOUR=17,
    SUGAR=18,
    PASTA=19,
    MIXES=20,
    WAFFLE=21,
    VEGETABLES=22,
    INDIVIDUALMEAL=23,
    ICECREAM=24,
    MEAT=25,
  }
  